- name: Configure my Mac
  hosts: local
  become: false

  tasks:
    - name: Install htop with Homebrew
      community.general.homebrew:
        name: htop
        state: present

    - name: Create a test file
      ansible.builtin.file:
        path: /tmp/ansible_test.txt
        state: touch

